@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Class AddressBook
Class UniqueTagList
Class UniquePersonList
Class Person
Class Tag
Class Name
Class Phone
Class Email
Class Address
Class Note
Class FollowUpDate
Class Circle

AddressBook *-right-> "1" UniqueTagList
UniqueTagList -right-> "*" Tag

AddressBook -down-> "1" UniquePersonList
UniquePersonList -right-> Person

Person -up-> "*" Tag

Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Address
Person *--> Note
Person *--> FollowUpDate
Person *--> Circle

UniqueTagList -[hidden]down-> UniquePersonList
Tag -[hidden]down-> Person

Name -[hidden]right-> Phone
Phone -[hidden]right-> Email
Email -[hidden]right-> Address
Address -[hidden]right-> Note
Note -[hidden]right-> FollowUpDate
FollowUpDate -[hidden]right-> Circle
@enduml
